language: rust
install:
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
- source ~/.nvm/nvm.sh
- nvm install v10.5
- curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
script:
- npm install
- npm run build-dev
deploy:
  provider: heroku
  on: master
  api_key:
    secure: mQ8cRt5AKpRS9tXPmk3027pGx/v7NgvVCiP2YYEFI3y2wooIAiFe+xuTi2kmRcXakI1FlhlxZoyKMu4IgUom09du0b73C65FcrjFQLme0rU08E5pzPMYlm6191seYEyUTzAIybnHmah8IUQHed4+guzlvMGijdu0QxyjdLtW6VG1tzY6FJwjCHienpjilVbWBGdjyjWqefmfjxkW5eerqwMFuYh5Z2Eww7eUi66701clTDa7oKBSZYpl347K4Z2vSTGpwUzBaMRrk4MLgjXvZPKUCD37Rc34iX6nPP2E8tnap/yIJOcK2t2GVSDyUWM9CSY8AUYs3GFWC339hJlG314UxFXV1jekTJkCLauYLxu6t90JRiOHKrK8JHJXk1jissF+t3qsQlivCpFTIP1hHfC7oSCNt126vvCdgXyENHPwG+TXdAFKU+3B2E/GYB0GoUBgZ47+esQEDZWNo9+BTQatHK/NezW4AgWsmLkE9+1ZEXCWN4hehq+CGlbFxlZJ/3kvgD9RZwhWifuaXN9n3Htuyi0PSftanvnJidO0uF2nGp5XOmlU4+w0y5UYO+oZNHDPoarJFMAE68lynQLVrWO2Z+FOjYwnopQ6zdCLHHjNs58KaP4e3dYercpI13JWjvnE/LBee/j2RDOi510+TgwSsJj4a2eULCHufB4eGus=
